# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Zemel
email: michael.zemel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sample projects and posts
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://masonbuilt.com" # the base hostname & protocol for your site
twitter_username: michael_zemel
github_username:  mzemel

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]