# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Zemel
email: michael.zemel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Projects and articles related to tech, travel, and fun
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://thebackend.dev" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.15.2"

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title

minimal-mistakes-skin: dirt

paginate: 10 # amount of posts to show
paginate_path: /page:num/

show_post_image_posts_list: false

# social
author:
  name: "Michael Zemel"
  short_bio:
    en: Software Engineer
  picture: assets/img/face.png
  avatar: "/assets/img/face.png"
  bio: "Public figure"
  location: "StitchFix"
  uri: "https://thebackend.dev"
  email: "michael.zemel@gmail.com"
  linkedin: "michael-zemel"
  instagram: "mzemel"
  github: "mzemel"
  twitter: "https://twitter.com/drunkonhemlock"
image: /assets/img/face.png
defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: games
      author_profile: true
      share: true
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles
      author_profile: true
      share: true
  -
    scope:
      type: "category"
    values:
      lang: "en"
      author_profile: true
